// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// spsign
arma::vec spsign(arma::vec x);
RcppExport SEXP _sike_spsign(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(spsign(x));
    return rcpp_result_gen;
END_RCPP
}
// spcov
arma::mat spcov(arma::mat X);
RcppExport SEXP _sike_spcov(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(spcov(X));
    return rcpp_result_gen;
END_RCPP
}
// kendalltau
arma::mat kendalltau(arma::mat X);
RcppExport SEXP _sike_kendalltau(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(kendalltau(X));
    return rcpp_result_gen;
END_RCPP
}
// hrstandardization
arma::mat hrstandardization(arma::mat X, double epsilon, unsigned maxiter);
RcppExport SEXP _sike_hrstandardization(SEXP XSEXP, SEXP epsilonSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< unsigned >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(hrstandardization(X, epsilon, maxiter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sike_spsign", (DL_FUNC) &_sike_spsign, 1},
    {"_sike_spcov", (DL_FUNC) &_sike_spcov, 1},
    {"_sike_kendalltau", (DL_FUNC) &_sike_kendalltau, 1},
    {"_sike_hrstandardization", (DL_FUNC) &_sike_hrstandardization, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_sike(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
